// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfsLhy9vHfUbSuDY9ZcYTcnKhBa_DFQX8',
    appId: '1:107015053698:web:5f9ce37fd3c76968c2af9b',
    messagingSenderId: '107015053698',
    projectId: 'sathuh-4ddcb',
    authDomain: 'sathuh-4ddcb.firebaseapp.com',
    storageBucket: 'sathuh-4ddcb.firebasestorage.app',
    measurementId: 'G-SCS3YVMDDQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpGQneco1TwXVFs1lKFsf4_NGGoswgD7g',
    appId: '1:107015053698:android:00adf4a1f88ac639c2af9b',
    messagingSenderId: '107015053698',
    projectId: 'sathuh-4ddcb',
    storageBucket: 'sathuh-4ddcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ZTExRXbOo3bK8TWnVpvjRupwmxbNNtc',
    appId: '1:107015053698:ios:e7a86f839c421579c2af9b',
    messagingSenderId: '107015053698',
    projectId: 'sathuh-4ddcb',
    storageBucket: 'sathuh-4ddcb.firebasestorage.app',
    iosBundleId: 'com.example.sathuh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ZTExRXbOo3bK8TWnVpvjRupwmxbNNtc',
    appId: '1:107015053698:ios:e7a86f839c421579c2af9b',
    messagingSenderId: '107015053698',
    projectId: 'sathuh-4ddcb',
    storageBucket: 'sathuh-4ddcb.firebasestorage.app',
    iosBundleId: 'com.example.sathuh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfsLhy9vHfUbSuDY9ZcYTcnKhBa_DFQX8',
    appId: '1:107015053698:web:00ec765e74bdb2eac2af9b',
    messagingSenderId: '107015053698',
    projectId: 'sathuh-4ddcb',
    authDomain: 'sathuh-4ddcb.firebaseapp.com',
    storageBucket: 'sathuh-4ddcb.firebasestorage.app',
    measurementId: 'G-Q1KZBZ9W06',
  );
}
